#! /usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
IFS=$'\n\t'

ROOT="/boot/firmware"

(
  cd "$HOME"

  if [[ -x "/boot/firmware/update" ]]; then
    "$ROOT/update"
  else
    printf "%s\n" "Skipped: Update script not found."
  fi

  for path in "$ROOT"/services/*; do
    printf "%s\n" "Running service: $path..."
    "$path"
  done
)
